### ISSUE TITLE
V3.0 (for dotCMS 3.7) - Add functionality to import/export csv stored in a content structre of type File

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-content-import-export#4]
V3.0 (for dotCMS 3.7) - Add functionality to import/export csv stored in a content structure of type File

Add a condition that allows the user to specify whether the csv file to be imported/exported will be read/saved: 
a) into a folder in the filesystem of the server running the plugin
b) as content under a specific file structure in dotCMS

If a), we need to request the user to enter the path of the filesystem folder (text field). If b), the user needs to specify the content type where the file will be read from or saved to (drop down of content structures of type File)

Importing/exporting content should keep happening in the same way after the csv file is obtained.

Iteration 1: Importing content (this is the most critical one for dEC clients at this point)
Iteration 2: Exporting content

**Comment by agomez-dotcms** [comment]
Hi Guys,

Iteration 1 (Importing content from File Assets) is now already code-complete. Plugin's edit-import screen has been enhanced with a Content Types dropdown where users can select which File Content Type should be queried for data-import purposes:

<img width="989" alt="screen shot 2017-02-16 at 3 11 04 pm" src="https://cloud.githubusercontent.com/assets/22307536/23041429/8e666582-f45a-11e6-9c61-44b5fd01d40a.png">

Back-end Job/Thread was also adjusted to incorporate this functionality as part of the processing. After a CSV file is imported from content, it becomes renamed with "csv.old" extension in order subsequent runs don't import it again. CVS Files may be uploaded as Content by different means, including following CURL command targeting REST API:

`curl -v -u admin@dotcms.com:admin -XPUT http://localhost:8080/api/content/publish/1 -F "json={stName:'fileAsset', hostFolder:'demo.dotcms.com:/resources', title:'Event_contents_2_16_2017.csv', fileName:'Event_contents_2_16_2017.csv'}; type=application/json" -F "file=@/Users/anibalgomez/Downloads/Events/Event_contents_2_16_2017.csv; type=application/csv"
`

Thanks,
Anibal

**Comment by agomez-dotcms** [comment]
PR: https://github.com/dotCMS/plugin-content-import-export/pull/5

**Comment by agomez-dotcms** [comment]
Hi Guys,

Enhancements performed as part of this ticket (explained above) are now successfully tested over Client's Production server ("https://prod-cms1.calvin.dotcmscloud.net/c"):
1. New File content-type was created to group CSV files to be processed ("CSV Events File")
2. New folder to upload CSV files to be processed ("upbeat.calvin.edu:/test/import/events")
3. New CSV files to be processed were uploaded via following CURL command:
`curl -k -v -u <username>:<password> -XPUT https://prod-cms1.calvin.dotcmscloud.net/api/content/publish/1 -F "json={stName:'CSVEventsFile', hostFolder:'upbeat.calvin.edu:/test/import/events', title:'Event_contents_2_17_2017-1.csv', fileName:'Event_contents_2_17_2017-1.csv'}; type=application/json" -F "file=@/Users/anibalgomez/Development/Clients/Calvin College/Event_contents_2_17_2017-1.csv; type=application/csv"
`
4. New Content Import Task/Job was created/scheduled (titled as "test new calendar import"). This job was configured with the new Content-Type option by targeting content-type "CSV Events File"

After running the Content Import Task/Job, final tests show that CSV files were imported in the system as expected. This concludes our preliminary tests for now

Thanks,
Anibal

**Comment by agomez-dotcms** [comment]
Hi Guys,

Iteration 2 (Exporting content to File Assets) is now already code-complete. Plugin's edit-export screen has been enhanced with a Content Types dropdown where users can select which File Content Type should be used for data-export purposes:

<img width="1100" alt="screen shot 2017-02-21 at 4 54 48 pm" src="https://cloud.githubusercontent.com/assets/22307536/23189196/6e783b82-f857-11e6-9142-6eac10af13c2.png">

Back-end Job/Thread was also adjusted to incorporate this functionality as part of the processing. After a export process is done, a new file asset with "csv" extension is exported into content as a File Asset.

Thanks,
Anibal
