### ISSUE TITLE
[Feature] File Upload Button

### ISSUE THREAD

**Issue by lucidmachine** [dotCMS/plugin-content-import-export#8]
Add a file upload button to the field "CSV File Source" in the portlet "EXT_STRUTS_CONTENT_IMPORT". When the user clicks this button and selects a file, upload that file to the server as a File Asset and use it as the CSV File Source for the Import Content job.

**Comment by gabbydotCMS** [comment]
We support csv import from file assets since V2.0 of the plugin.
